#!/bin/sh

# PROVIDE: gmirror_balance_algo
# REQUIRE: savecore gmirror_prefer_algo
# BEFORE:
# KEYWORD: nojail

. etc/rc.subr

name=gmirror_balance_algo
desc="Sets gmirror balance algorithm"
rcvar=gmirror_prefer_algo_enable

start_cmd="${name}_start"
stop_cmd=":"
load_rc_config $name
: ${gmirror_prefer_algo_enable="NO"}
: ${gmirror_prefer_algo_mirror=""}
: ${gmirror_balance_algo="load"}

gmirror_balance_algo_start()
{
    balance_cmd="gmirror configure -b ${gmirror_balance_algo} ${gmirror_prefer_mirror}"
    $balance_cmd
}

run_rc_command "$1"
